server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ingestion-service

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/phylax}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info
